### ISSUE TITLE
Pangalingi kasutamine

### ISSUE THREAD

**Issue by saaruniversity** [vtlkzmn/VeebirakendusteLoomine#17]

**Comment by ghost** [comment]
Minnes lehele /dbqueryview saab teha päringu. Minnes tagasi kaupmehe juurde, kuvatakse vastavalt kas payment successful või canceled. Nupp kodulehele redirectimiseks. Juhised kasutamiseks siin: https://packagist.org/packages/talandis/laravel-banklinks, testimiseks vaja ka http://pangalink.net/
