### ISSUE TITLE
mitmekeelne kasutajaliides

### ISSUE THREAD

**Issue by saaruniversity** [vtlkzmn/VeebirakendusteLoomine#21]

**Comment by ghost** [comment]
Headeri tekstid on tõlgitud, rohkem ei viitsinud. Keeltefailid asuvad vastavalt /resources/lang/en ja /resources/lang/en.  Tõlkimine toimub Blade-i snippetiga strtoupper(trans('header.contact')), kus trans-translate; otsib currentLocale-i  kaustast faili header.php ning sealt sissekannet contact.
